### ISSUE TITLE
R5 cleanup: Update the FHIR build process to reflect R5 RDF changes

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#110]
RDF model changes made in R5:
- RDF lists
- De-curry value[x] properties
- Shorten resource properties: fhir:Observation.reference --> fhir:reference
- Shorten datatype properties: fhir:Observation.status --> fhir:status
- Modifier extensions

From Lloyd in zulip on 14-Nov-2022: **"Final content freeze is slated for Feb. 24, 2023"**

R5 bug fixes:

- [ ] Change FHIR examples to use xsd:anyURI as shown [here](https://github.com/ericprud/validation/commit/ae9740bdbd07dc685de0e51eadba1963351c27c1).

Artifacts to be updated:

- FHIR build products:
  - [x] Downloads page: change "Definitions" to "Ontology" -- David https://jira.hl7.org/browse/FHIR-39072
  - [x] FHIR ontology -- Daniel https://jira.hl7.org/browse/FHIR-39073
    - [x] And Add ontology property relationships to underscore properties: value → _value
  - [x] ShEx -- Deepak  https://jira.hl7.org/browse/FHIR-39074
  - [x] Examples -- Jim https://jira.hl7.org/browse/FHIR-39075
  - [x] Resource templates -- Jim  https://jira.hl7.org/browse/FHIR-39076
  - [ ] Turtle parser for FHIR validator org.hl7.fhir.r5.elementmodel.TurtleParser.  See [Grahame's comments.](https://chat.fhir.org/#narrow/stream/279829-rdf/topic/Pull.20requests.20for.20R5.20FHIR.20RDF.20changes/near/328160229) -- Jim [github issue](https://github.com/hapifhir/org.hl7.fhir.core/issues/1119)   -- Addressing this in a separate issue
- FHIR documentation:
  - [ ] <del>Add "What's New in FHIR RDF" to FAQ managed by FHIR-I group?</del> -- Not yet, per 2/1/23 email from Davera.  7/27/23: Moved to https://github.com/w3c/hcls-fhir-rdf/issues/124
  - [x] FHIR home page: add link to rdf.html -- David  https://jira.hl7.org/browse/FHIR-39077
  - [x] (NEXT: ITS vote) Extensions page -- David  https://jira.hl7.org/browse/FHIR-39078
  - [x] (NEXT: ITS vote) rdf.html: Add https://build.fhir.org/rdf.html#iri-stem anchor, and explain its purpose -- David https://jira.hl7.org/browse/FHIR-40269
  - [x] (NEXT: ITS vote) rdf.html: Fix broken link to RDF lists scripts.  It should be https://github.com/w3c/hcls-fhir-rdf/tree/gh-pages/scripts/owl-safe-lists -- David  https://jira.hl7.org/browse/FHIR-40269
  - [x] Add example of a code with non-latin characters -- Eric https://jira.hl7.org/browse/FHIR-38071
- Code:
  - [ ] HAPI parser/generator -- EricP  -- 7/27/23: Moved to https://github.com/w3c/hcls-fhir-rdf/issues/125
  - [x] SPARQL Script to convert R5 RDF to OWL-and-SPARQL-friendly RDF -- Jim
  - [ ] Update the [SPARQL scripts](https://github.com/w3c/hcls-fhir-rdf/tree/gh-pages/scripts/owl-safe-lists) to add the OWL ontology declarations: `<http://hl7.org/fhir/Observation/Obs123.ttl> a owl:Ontology;   owl:imports fhir:fhir.ttl;   owl:versionIRI <http://hl7.org/fhir/Observation/Obs123.ttl>.` -- 7/27/23: Moved to https://github.com/w3c/hcls-fhir-rdf/issues/126
    - [ ] Add to explanation to rdf.html page: "1. apply the RDF list SPARQL update transformation to your data file. 2. Merge the ontology into your data file. 3. Open in Protege. "  Per Jim: But then it will still be very hard to navigate since all individuals are anonymous. Maybe we should also provide a SPARQL update to swap in skolem IRIs for all individuals -- Moved to https://github.com/w3c/hcls-fhir-rdf/issues/128
  - [x] FHIR RDF Playground: Simplify the UI to have R4 vs R5 option instead of multiple individual options.  But keep the individual options somewhere, in case somebody wants to use them, for example to disable RDF lists for OWL safety. -- James
  - [ ] FHIR RDF Playground: [Properly translate modifier extensions for R5 (and R4)](https://github.com/w3c/hcls-fhir-rdf/issues/112) -- James  -- To be addressed in issue 112
  - [ ] FHIR RDF Playground: Fix [primitive extensions](https://github.com/w3c/hcls-fhir-rdf/issues/113) -- James??? -- To be addressed
  - [ ] FHIR RDF Playground: Add show/hide toggle for middle (JSON-LD) window. -- 7/27/23: Implemented, but has a bug: https://github.com/w3c/hcls-fhir-rdf/issues/129
  - [ ] FHIR RDF Playground: Add FHIR RDF validation capability. -- Houcemeddine Turki -- 7/27/23: Moved to https://github.com/w3c/hcls-fhir-rdf/issues/130

Concept IRI tasks:
- [x] Complete UTG proposal to add IRI stems to LOINC (https://jira.hl7.org/browse/UP-364)
  - [x] Complete draft and make sure everybody on the call is happy with it
  - [x] Write some code that implements this change in Sourcetree
  - [x] Solicit feedback from TSMG/Vocab
  - [x] Find someone to review and accept these changes (for LOINC)
- [x] Complete proposal
  - [x] It looks like we can incorporate the text I've written in the Google Doc into one of our existing proposals rather than creating a new proposal -- will need to look into this.

7/27/23: Gaurav is following up on these:
- [ ] Add IRI stems for as many HL7 Terminologies as possible
  - [ ] Make a list of HL7 CodeSystems and NamingSystems on terminology.hl7.org (THO)
  - [ ] Identify the best IRI stem for as many of the code systems
  - [ ] Submit a UTG proposal to make all of those changes in line with the previously proposed

Update process:
1. Create jira tickets for desired changes.  But do not assign to self (or it goes into "Waiting for Input" state) until AFTER it is resolved and voted!
2. Get ITS to vote them  (done 17-Aug-2022 for substantive changes; need to do it also for editorial changes)
3. Submit a PR for the proposed change (which will normally be merged by yourself)
4. Wait for automated build checks to pass
5. Merge the PR
6. In Jira, use Workflow->Will Update Spec to record the vote and resolution.   In Jira, use "Propose Disposition" button to propose a resolution and mark the changes a pre-applied.  Also record the commit tag in a comment.  (Sometimes this can be done before ITS votes, e.g., if it's fixing a typo, in which case the ticket should be marked 'Pre-applied'.  But major code changes should be voted by ITS first.)
7. (If UTG proposal for THO update): (Jira ticket will have "up-" prefix.) Get it into "consensus review" state, then get people to vote it.  Once enough votes are in favor, THO will take it from there.
8. DONE!

NOTE: Editorial changes that follow the spirit of the semantic change decision are also okay.  Make a note of what is done.   If it appears that the voted decision was incorrect, then it needs to go back to ITS for vote again.

**Comment by balhoff** [comment]
Here is my candidate SPARQL update for transforming RDF lists to a different namespace (to avoid OWL spec violations). This update should only be applied to an RDF file where all the lists are "data", and not part of OWL axiom definitions.

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fhir: <http://hl7.org/fhir/>
DELETE {
  ?list rdf:first ?item .
  ?list rdf:rest ?rest .
}
INSERT {
  ?list ?first_pred ?item .
  ?list fhir:rdfRest ?rest_obj .
}
WHERE {
  ?list rdf:first ?item .
  ?list rdf:rest ?rest .
  BIND(IF(isLiteral(?item), fhir:rdfFirstLiteral, fhir:rdfFirst) AS ?first_pred)
  BIND(IF(?rest = rdf:nil, fhir:rdfNil, ?rest) AS ?rest_obj)
}
```

Test input:

```turtle
@prefix : <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

:a :has_addresses (
    [
      :street "1428 Elm Street" ;
      :state :Ohio
    ]
    [
      :street "2400 Fulton Street" ;
      :state :California
    ]
    "Sesame Street"
    :PlanetEarth
  ) ;
  rdfs:label "Person A" .
```

Test output:

```turtle
@prefix :     <http://example.org/> .
@prefix fhir: <http://hl7.org/fhir/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

:a      rdfs:label      "Person A" ;
        :has_addresses  [ fhir:rdfFirst  [ :state   :Ohio ;
                                           :street  "1428 Elm Street"
                                         ] ;
                          fhir:rdfRest   [ fhir:rdfFirst  [ :state   :California ;
                                                            :street  "2400 Fulton Street"
                                                          ] ;
                                           fhir:rdfRest   [ fhir:rdfFirstLiteral  "Sesame Street" ;
                                                            fhir:rdfRest          [ fhir:rdfFirst  :PlanetEarth ;
                                                                                    fhir:rdfRest   fhir:rdfNil
                                                                                  ]
                                                          ]
                                         ]
                        ] .
```

**Comment by dbooth-boston** [comment]
@balhoff , how about adding another condition to the WHERE clause to ensure that it is applied only to FHIR lists (and not part of OWL axiom definitions)?

**Comment by balhoff** [comment]
> @balhoff , how about adding another condition to the WHERE clause to ensure that it is applied only to FHIR lists (and not part of OWL axiom definitions)?

@dbooth-boston good idea, I've got a revision now. Do we have a proper location to put this in our repo? In here? https://github.com/w3c/hcls-fhir-rdf/tree/gh-pages/scripts

**Comment by gaurav** [comment]
Concept IRI tasks:
- [ ] Complete UTG proposal to add IRI stems to LOINC (https://jira.hl7.org/browse/UP-364)
  - [ ] Complete draft and make sure everybody on the call is happy with it
  - [ ] Write some code that implements this change in Sourcetree
  - [ ] Solicit feedback from TSMG/Vocab
  - [ ] Find someone to review and accept these changes (for LOINC)
- [ ] Complete proposal
  - [ ] It looks like we can incorporate the text I've written in the Google Doc into one of our existing proposals rather than creating a new proposal -- will need to look into this.
- [ ] Add IRI stems for as many HL7 Terminologies as possible
  - [ ] Make a list of HL7 CodeSystems and NamingSystems on terminology.hl7.org (THO)
  - [ ] Identify the best IRI stem for as many of the code systems
  - [ ] Submit a UTG proposal to make all of those changes in line with the previously proposed

**Comment by dbooth-boston** [comment]
Done (enough) or moved to separate issues for remaining portions.
