### ISSUE TITLE
json-ld 1.1 preprocessing checklist

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#86]
We might want to break this into separate issues, but I thought I would experiment with github's new-ish checklist feature.  

These are known issues that we'll need to address in a JSON preprocessor.  Please add to these if you think of more.

- [x] Map fhir:valueX properties to RDF datatypes.  See slide 5: https://lists.w3.org/Archives/Public/www-archive/2019Nov/att-0000/FHIRRdf.pdf
- [ ] Connect FHIR extension element "_foo" to element "foo", so that an RDF query can traverse from any element ?foo to its extensions, without hard-coding the element names.  See slide 8: https://lists.w3.org/Archives/Public/www-archive/2019Nov/att-0000/FHIRRdf.pdf  See #77
- [x] Runtime type determination of dateTime union types.  fhir:valueDate and valueDateTime (any others?) require runtime inspection of the value in order to determine the specific RDF type that was used.  See #78
- [x] Runtime type determination of number union types: xsd:int, xsd:decimal, xsd:double.  See #99
- [x] Retain significant digits in decimals, such as "1.000" versus "1.0".  See #92   Note in #92 that we decided not to fix this.
- [x] Add fhir:nodeRole fhir:treeRoot .  See https://www.hl7.org/fhir/rdf.html
- [x] Add `id` elements that get removed by `@id` conversion to URIs.  This is needed because when the FHIR/JSON says `"id": "abc123"` is an `@id` in the `@context`, it becomes the URI of the element, which means that the "id" string property is lost.  Preprocessing can replicate the property  to enable it to both stay as a string and become a URI.
- [x] Add fhir:link properties.  See https://www.hl7.org/fhir/rdf.html#reference
- [x] Add types of Concept references.  See https://www.hl7.org/fhir/rdf.html#concept

**Comment by dbooth-boston** [comment]
Relevant to the "union types" sub-issue, here's an example of how to handle union types in JSON-LD: https://tinyurl.com/2p88swzd

http://build.fhir.org/datatypes.html#dateTime 

The problem of union types was described in issue #78

**Comment by dbooth-boston** [comment]
Done in R5
